import { Country } from '../types';

// This static data replaces the live API call for the country list,
// making the initial application load instant and removing the source of network errors.
// The 'apiId' is the UUID required by the DIDWW API to fetch requirements.
export const staticCountries: Country[] = [
    { id: 'AL', iso: 'AL', name: 'Albania', needs_registration: true, local_national_price: 30.00, apiId: 'eae2225e-732e-4212-b547-7a64c47d887e' },
    { id: 'AR', iso: 'AR', name: 'Argentina', needs_registration: true, local_national_price: 6.00, apiId: '6ca02513-d3a1-4875-98fd-e328027de867' },
    { id: 'AU', iso: 'AU', name: 'Australia', needs_registration: true, local_national_price: 5.00, mobile_price: 15.00 },
    { id: 'AT', iso: 'AT', name: 'Austria', needs_registration: true, local_national_price: 5.00 },
    { id: 'BE', iso: 'BE', name: 'Belgium', needs_registration: true, local_national_price: 5.00, mobile_price: 10.00 },
    { id: 'BO', iso: 'BO', name: 'Bolivia', needs_registration: true, local_national_price: 52.00 },
    { id: 'BA', iso: 'BA', name: 'Bosnia and Herzegovina', needs_registration: true, local_national_price: 6.00 },
    { id: 'BR', iso: 'BR', name: 'Brazil', needs_registration: true, mobile_needs_registration: false, local_national_price: 6.00, mobile_price: 10.00 },
    { id: 'BG', iso: 'BG', name: 'Bulgaria', needs_registration: true, local_national_price: 10.00 },
    { id: 'CA', iso: 'CA', name: 'Canada', needs_registration: false, local_national_price: 5.00 },
    { id: 'CL', iso: 'CL', name: 'Chile', needs_registration: true, local_national_price: 8.00, mobile_price: 10.00 },
    { id: 'CN', iso: 'CN', name: 'China', needs_registration: true, local_national_price: 20.00 },
    { id: 'CO', iso: 'CO', name: 'Colombia', needs_registration: true, mobile_needs_registration: false, local_national_price: 20.00, mobile_price: 20.00 },
    { id: 'CR', iso: 'CR', name: 'Costa Rica', needs_registration: true, local_national_price: 15.00, apiId: '2258abe9-ddc4-45b8-9385-44bac01a4037' },
    { id: 'HR', iso: 'HR', name: 'Croatia', needs_registration: true, local_national_price: 5.00 },
    { id: 'CY', iso: 'CY', name: 'Cyprus', needs_registration: true, local_national_price: 9.00 },
    { id: 'CZ', iso: 'CZ', name: 'Czech Republic', needs_registration: true, local_national_price: 5.00 },
    { id: 'DK', iso: 'DK', name: 'Denmark', needs_registration: true, mobile_needs_registration: false, local_national_price: 5.00, mobile_price: 10.00 },
    { id: 'DO', iso: 'DO', name: 'Dominican Republic', needs_registration: true, local_national_price: 10.00 },
    { id: 'EC', iso: 'EC', name: 'Ecuador', needs_registration: true, mobile_needs_registration: false, mobile_price: 52.00 },
    { id: 'SV', iso: 'SV', name: 'El Salvador', needs_registration: true, local_national_price: 15.00 },
    { id: 'EE', iso: 'EE', name: 'Estonia', needs_registration: true, local_national_price: 6.00 },
    { id: 'FI', iso: 'FI', name: 'Finland', needs_registration: true, local_national_price: 5.00, mobile_price: 10.00 },
    { id: 'FR', iso: 'FR', name: 'France', needs_registration: true, local_national_price: 5.00 },
    { id: 'GE', iso: 'GE', name: 'Georgia', needs_registration: true, local_national_price: 12.00 },
    { id: 'DE', iso: 'DE', name: 'Germany', needs_registration: true, local_national_price: 5.00 },
    { id: 'GR', iso: 'GR', name: 'Greece', needs_registration: true, local_national_price: 5.00 },
    { id: 'GT', iso: 'GT', name: 'Guatemala', needs_registration: false, local_national_price: 15.00 },
    { id: 'HN', iso: 'HN', name: 'Honduras', needs_registration: true, local_national_price: 35.00 },
    { id: 'HK', iso: 'HK', name: 'Hong Kong', needs_registration: true, local_national_price: 15.00, apiId: '9d72aa39-9510-4d8c-ab41-28ee3d79df3a' },
    { id: 'HU', iso: 'HU', name: 'Hungary', needs_registration: true, local_national_price: 8.00 },
    { id: 'IS', iso: 'IS', name: 'Iceland', needs_registration: false, local_national_price: 10.00 },
    { id: 'ID', iso: 'ID', name: 'Indonesia', needs_registration: true, local_national_price: 38.00 },
    { id: 'IE', iso: 'IE', name: 'Ireland', needs_registration: true, local_national_price: 5.00 },
    { id: 'IL', iso: 'IL', name: 'Israel', needs_registration: false, local_national_price: 5.00, mobile_price: 5.00 },
    { id: 'IT', iso: 'IT', name: 'Italy', needs_registration: true, local_national_price: 5.00 },
    { id: 'JP', iso: 'JP', name: 'Japan', needs_registration: true, local_national_price: 9.00 },
    { id: 'KE', iso: 'KE', name: 'Kenya', needs_registration: true, local_national_price: 15.00 },
    { id: 'LV', iso: 'LV', name: 'Latvia', needs_registration: true, local_national_price: 5.00 },
    { id: 'LT', iso: 'LT', name: 'Lithuania', needs_registration: true, local_national_price: 5.00, mobile_price: 5.00 },
    { id: 'LU', iso: 'LU', name: 'Luxembourg', needs_registration: true, local_national_price: 5.00 },
    { id: 'MY', iso: 'MY', name: 'Malaysia', needs_registration: true, local_national_price: 20.00 },
    { id: 'MT', iso: 'MT', name: 'Malta', needs_registration: true, local_national_price: 10.00 },
    { id: 'MX', iso: 'MX', name: 'Mexico', needs_registration: true, local_national_price: 8.00, mobile_price: 10.00 },
    { id: 'NL', iso: 'NL', name: 'Netherlands', needs_registration: true, mobile_needs_registration: false, local_national_price: 5.00, mobile_price: 5.00 },
    { id: 'NZ', iso: 'NZ', name: 'New Zealand', needs_registration: false, local_national_price: 5.00 },
    { id: 'NI', iso: 'NI', name: 'Nicaragua', needs_registration: true, mobile_price: 35.00 },
    { id: 'NG', iso: 'NG', name: 'Nigeria', needs_registration: true, local_national_price: 16.00 },
    { id: 'MK', iso: 'MK', name: 'North Macedonia', needs_registration: true, local_national_price: 6.00 },
    { id: 'NO', iso: 'NO', name: 'Norway', needs_registration: true, local_national_price: 5.00 },
    { id: 'PA', iso: 'PA', name: 'Panama', needs_registration: false, local_national_price: 10.00 },
    { id: 'PE', iso: 'PE', name: 'Peru', needs_registration: true, mobile_needs_registration: false, local_national_price: 12.00, mobile_price: 10.00 },
    { id: 'PL', iso: 'PL', name: 'Poland', needs_registration: true, local_national_price: 5.00, mobile_price: 10.00 },
    { id: 'PT', iso: 'PT', name: 'Portugal', needs_registration: true, local_national_price: 5.00 },
    { id: 'PR', iso: 'PR', name: 'Puerto Rico', needs_registration: false, local_national_price: 12.00 },
    { id: 'RO', iso: 'RO', name: 'Romania', needs_registration: true, local_national_price: 5.00 },
    { id: 'RS', iso: 'RS', name: 'Serbia', needs_registration: true, local_national_price: 6.00 },
    { id: 'SG', iso: 'SG', name: 'Singapore', needs_registration: true, local_national_price: 8.00 },
    { id: 'SK', iso: 'SK', name: 'Slovakia', needs_registration: true, mobile_needs_registration: false, local_national_price: 5.00, mobile_price: 35.00 },
    { id: 'SI', iso: 'SI', name: 'Slovenia', needs_registration: true, local_national_price: 5.00 },
    { id: 'ZA', iso: 'ZA', name: 'South Africa', needs_registration: true, local_national_price: 5.00, mobile_price: 10.00 },
    { id: 'ES', iso: 'ES', name: 'Spain', needs_registration: true, local_national_price: 5.00 },
    { id: 'SE', iso: 'SE', name: 'Sweden', needs_registration: true, local_national_price: 5.00, mobile_price: 10.00 },
    { id: 'CH', iso: 'CH', name: 'Switzerland', needs_registration: true, local_national_price: 5.00 },
    { id: 'TH', iso: 'TH', name: 'Thailand', needs_registration: true, local_national_price: 15.00, mobile_price: 20.00 },
    { id: 'UG', iso: 'UG', name: 'Uganda', needs_registration: true, local_national_price: 15.00 },
    { id: 'UA', iso: 'UA', name: 'Ukraine', needs_registration: true, mobile_needs_registration: false, local_national_price: 20.00, mobile_price: 5.00 },
    { id: 'GB', iso: 'GB', name: 'United Kingdom', needs_registration: false, local_national_price: 5.00, mobile_price: 5.00 },
    { id: 'US', iso: 'US', name: 'United States', needs_registration: false, local_national_price: 5.00 },
    { id: 'VE', iso: 'VE', name: 'Venezuela', needs_registration: true, local_national_price: 15.00 },
].filter(c => c.local_national_price !== undefined);
